name: pratice

on: 
 push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: chekout
        uses: actions/checkout@v6

      - name: files
        run: ls -la
     
         
    
                    

