name: pratice

on: 
    branches:
            push: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
         -name: checkout
         -uses: actions/checkout@v6
        
         -name: files
         -run: ls -la
             
    
                    

