name: github
on: push
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SECRETS_HOST }}
          username: ${{ secrets.SECRETS_USERNAME }}
          key: ${{ secrets.SECRETS_KEY }}
          script: sudo yum update -y
    

  
  
         
    
                    

